routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
Route::resource('productos', 'App\Http\Controllers\ProductoController');
Route::resource('categoria', 'App\Http\Controllers\CategoriaController');
Route::resource('venta', 'App\Http\Controllers\VentaController');
Route::get('/reporteVentas', 'App\Http\Controllers\VentaController@reportes')->name('reporteVenta');
Route::post('/buscarProductoVenta', 'App\Http\Controllers\VentaController@buscarProductoVenta')->name('buscarProductoVenta');
Route::post('/agregarProductoVenta', 'App\Http\Controllers\VentaController@agregarProductoVenta')->name('agregarProductoVenta');
Route::delete('/quitarProductoVenta', 'App\Http\Controllers\VentaController@quitarProductoVenta')->name('quitarProductoVenta');
Route::resource('entradas', 'App\Http\Controllers\EntradasController');
Route::get('/reporteCompras', 'App\Http\Controllers\EntradasController@reportes')->name('reporteCompra');
Route::post('/buscarProducto', 'App\Http\Controllers\EntradasController@buscarProducto')->name('buscarProducto');
Route::post('/agregarProducto', 'App\Http\Controllers\EntradasController@agregarProducto')->name('agregarProducto');
Route::delete('/quitarProducto', 'App\Http\Controllers\EntradasController@quitarProducto')->name('quitarProducto');

app/Models/Entrada.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Entrada extends Model
{
    use HasFactory;

    protected $fillable = [
        'fecha', 'total', 'status'
    ];
    public function detalle()
    {
        return $this->hasMany(DetalleEntrada::class);
    }
}

app/Http/Controllers/EntradasController.php
<?php

namespace App\Http\Controllers;

use App\Models\DetalleEntrada;
use App\Models\Entrada;
use App\Models\Producto;
use Illuminate\Http\Request;

class EntradasController extends Controller
{
    public function index(){
        $total = 0;
        foreach ($this->obtenerProductos() as $producto) {
            $total += $producto->existencia * $producto->precio;
        }
        return view('entradas.index',['total' => $total]);
    }

    public function store(Request $request){
        $entrada = Entrada::create([
            'fecha' => date("Y-m-d H:i:s"),
            'total' => 00.00,
            'status' => 1
        ]);
        $productos = $this->obtenerProductos();
        $total = 0;
        foreach ($productos as $producto) {
            $detalle = new DetalleEntrada();
            $detalle->fill([
                'entrada_id' => $entrada->id,
                'producto_id' => $producto->id,
                'costo_unitario' => $producto->precio,
                'cantidad' => $producto->existencia
            ]);
            $detalle->saveOrFail();
            $total_producto = $producto->precio * $producto->existencia;
            $total = $total + $total_producto;
            $productoActualizado = Producto::find($producto->id);
            $productoActualizado->existencia += $detalle->cantidad;
            $productoActualizado->saveOrFail();
        }
        $this->vaciarProductos();
        $entrada->update([
            'total' => $total,
            'status' => 3,
        ]);
        return redirect()->route('home')->with('message', 'Registro completo');
    }

    public function reportes(){
        $compras = Entrada::all();
        $data = [
            'entradas' => $compras
        ];
        return view('entradas.reportes')->with($data);
    }

    public function show($id){
        $producto = Producto::where('codigo','=',$id)->get();
        return response()->json($producto[0]);
    }

    public function buscarProducto(Request $request){
        $codigo = $request->post('codigo');
        $producto = Producto::where('codigo', '=', $codigo)->first();
        if (!$producto) {
            return redirect()
                ->route('entradas.index')->with('error', 'Producto no encontrado');
        }
        return redirect()->route('entradas.index')->with('producto',$producto);
    }

    private function obtenerProductos(){
        $productos = session("productos");
        if (!$productos) {
            $productos = [];
        }
        return $productos;
    }

    public function agregarProducto(Request $request){
        $producto = Producto::find($request->id);
        $producto->existencia = $request->cantidad;
        $producto->precio = $request->precio;
        $productos = $this->obtenerProductos();
            array_push($productos, $producto);
        $this->guardarProductos($productos);
        return redirect()->route('entradas.index');
    }

    private function guardarProductos($productos){
        session(["productos" => $productos,
        ]);
    }

    public function quitarProducto(Request $request){
        $indice = $request->post("indice");
        $productos = $this->obtenerProductos();
        array_splice($productos, $indice, 1);
        if(sizeof($productos) <= 0){
            $this->vaciarProductos();
        }else{
            $this->guardarProductos($productos);
        }
        return redirect()->route('entradas.index');
    }

    private function vaciarProductos(){
        $this->guardarProductos(null);
    }

}

resources/views/entradas/index.blade.php
@extends('layout.app')

@push('styles')
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
@endpush

@section('header')
<div class="mx-5">
    <div class="row mb-2">
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-start">
                <li class="breadcrumb-item">
                    <a href="/">Inicio</a>
                </li>
                <li class="breadcrumb-item active">
                   Mercancia <i class="fas fa-shopping-bag"></i>
                </li>
            </ol>
        </div>
        <div class="col-sm-6 text-end mt-3">
            <a href="/"><button class="btn btn-outline-dark btn-lg"> <i class="fas fa-arrow-left"></i> Regresar</button></a>
        </div>
    </div>
    <hr>
</div>
@endsection
@section('content')
<div class="row">
    <div class="col-md-12 pb-3 pt-3">
        <div class="card">
            <div class="card-header text-center bg-title">
                <h1 class="fs-4 fw-bold">Capturar compras de mercancía</h1>
            </div>
            <div class="card-body">
                <div class="col-12 col-md-12">
                    <form action="{{route("buscarProducto")}}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="codigo">Código de barras</label>
                            <input id="codigo" autocomplete="off" required autofocus name="codigo" type="text" class="form-control" placeholder="Código de barras">
                        </div>
                    </form>
                    @if (Session::has('producto'))
                        <form class="form-group" action="{{ route('agregarProducto') }}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-md-6 mt-2">
                                    <div class="form-group">
                                        <label for="codigo">Código de barras</label>
                                        <input type="text" class="form-control" id="codigo" name="codigo" placeholder="Ingresar codigo de barras" value="{{ session('producto')->codigo }}" disabled>
                                        <input type="text" class="form-control" id="id" name="id" value="{{ session('producto')->id }}" hidden>
                                    </div>
                                </div>
                                <div class="col-md-6 mt-2">
                                    <div class="form-group">
                                        <label for="nombre">Nombre</label>
                                        <input type="text" class="form-control" id="nombre" name="nombre" value="{{ session('producto')->nombre }}" disabled>
                                    </div>
                                </div>
                                <div class="col-md-6 mt-2">
                                    <div class="form-group">
                                        <label for="cantidad">Cantidad</label>
                                        <input type="text" class="form-control" id="cantidad" name="cantidad" placeholder="Cantidad a registrar" autofocus required>
                                    </div>
                                </div>
                                <div class="col-md-6 mt-2">
                                    <div class="form-group">
                                        <label for="precio">Precio Unitario</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text">$</span>
                                            </div>
                                            <input type="text" class="form-control" id="precio" name="precio" required autofocus>
                                            <div class="input-group-append">
                                                <span class="input-group-text">.00</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="mt-3 text-end">
                                    <button type="submit" class="btn btn-primary"><i class="far fa-save"></i> Agregar</button>
                                </div>
                            </div>
                        </form>
                    @endif
                </div>
                @if (Session::has('productos'))
                    <div class="col-md-12 mt-5">
                        <h2>Total: ${{number_format($total, 2)}}</h2>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Código de barras</th>
                                        <th>Descripción</th>
                                        <th>Precio</th>
                                        <th>Cantidad</th>
                                        <th>Quitar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach(session("productos") as $producto)
                                        <tr>
                                            <td>{{ $producto->codigo }}</td>
                                            <td>{{ $producto->nombre }}</td>
                                            <td>$ {{ $producto->precio }}</td>
                                            <td>{{ $producto->existencia }}</td>
                                            <td>
                                                <form action="{{route("quitarProducto")}}" method="post">
                                                    @method("delete")
                                                    @csrf
                                                    <input type="hidden" name="indice" value="{{$loop->index}}">
                                                    <button type="submit" class="btn btn-danger">
                                                        <i class="fa fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                @endif
            </div>
            <div class="card-footer text-end">
                @if (Session::has('productos'))
                    <form action="{{ route('entradas.store') }}" method="POST">
                        @csrf
                        <button type="submit" class="btn btn-success"><i class="far fa-save"></i> Terminar registro</button>
                    </form>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/entradas/reportes.blade.php
@extends('layout.app')

@push('styles')
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
@endpush

@section('header')
    <div class="mx-5">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-start">
                    <li class="breadcrumb-item">
                        <a href="/">Inicio</a>
                    </li>
                    <li class="breadcrumb-item active">
                    Reporte de compras <i class="fas fa-paste"></i>
                    </li>
                </ol>
            </div>
            <div class="col-sm-6 text-end mt-3">
                <a href="/"><button class="btn btn-outline-dark btn-lg"> <i class="fas fa-arrow-left"></i> Regresar</button></a>
            </div>
        </div>
        <hr>
    </div>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12 pb-3 pt-3">
            <div class="card">
                <div class="card-header text-center bg-title">
                    <h1 class="fs-4 fw-bold">Reporte de compras</h1>
                </div>
                <div class="card-boy">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover dataTables-compras">
                            <thead>
                                <tr>
                                    <th>Fecha de compra</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($entradas as $entrada)
                                <tr>
                                   <td>{{ $entrada->created_at }}</td>
                                   <td>{{ $entrada->total }}</td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Fecha de compra</th>
                                    <th>Total</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <div class="card-footer text-end"></div>
            </div>
        </div>
    </div>
    @push('scripts')
   <script src="{{ asset('js/datatables.min.js') }}"></script>
   <script>
       $(document).ready(function(){
        $('.dataTables-compras').DataTable();
    });
   </script>
@endpush
@endsection