routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Route::get('/', 'App\Http\Controllers\HomeController@index')->name('home');
Route::resource('productos', 'App\Http\Controllers\ProductoController');
Route::resource('categoria', 'App\Http\Controllers\CategoriaController');
Route::resource('venta', 'App\Http\Controllers\VentaController');
Route::get('/reporteVentas', 'App\Http\Controllers\VentaController@reportes')->name('reporteVenta');
Route::post('/buscarProductoVenta', 'App\Http\Controllers\VentaController@buscarProductoVenta')->name('buscarProductoVenta');
Route::post('/agregarProductoVenta', 'App\Http\Controllers\VentaController@agregarProductoVenta')->name('agregarProductoVenta');
Route::delete('/quitarProductoVenta', 'App\Http\Controllers\VentaController@quitarProductoVenta')->name('quitarProductoVenta');
Route::resource('entradas', 'App\Http\Controllers\EntradasController');
Route::get('/reporteCompras', 'App\Http\Controllers\EntradasController@reportes')->name('reporteCompra');
Route::post('/buscarProducto', 'App\Http\Controllers\EntradasController@buscarProducto')->name('buscarProducto');
Route::post('/agregarProducto', 'App\Http\Controllers\EntradasController@agregarProducto')->name('agregarProducto');
Route::delete('/quitarProducto', 'App\Http\Controllers\EntradasController@quitarProducto')->name('quitarProducto');

app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    use HasFactory;
    protected $fillable = [
        'nombre','status'
    ];

    public function productos()
    {
        return $this->hasMany(Prouducto::class);
    }
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categoria;
use Illuminate\Http\Request;

class CategoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'categorias' => Categoria::all(),
        ];
        return view('categoria\index')->with($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre' => 'required|max:50'
        ]);
        $categoria = Categoria::create([
            'nombre' => $request->nombre
        ]);
        return back()->with('message', 'Nueva categoria agregada');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categoria/index.blade.php
@extends('layout\app')

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/styles.css') }}">
    {{-- <link rel="stylesheet" href="{{ asset('css/datatables.min.css') }}"> --}}
@endpush

@section('header')
<div class="mx-5">
    <div class="row mb-2">
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-start">
                <li class="breadcrumb-item">
                    <a href="/">Inicio</a>
                </li>
                <li class="breadcrumb-item active">
                   Categorias <i class="fas fa-th-list"></i>
                </li>
            </ol>
        </div>
        <div class="col-sm-6 text-end mt-3">
            <a href="/"><button class="btn btn-outline-dark btn-lg"> <i class="fas fa-arrow-left"></i> Regresar</button></a>
        </div>
    </div>
    <hr>
</div>
@endsection

@section('content')
<!-- Header-->
<div class="row">
    <div class="col-md-8 pb-0">
        <div class="card">
            <div class="card-header text-center bg-title">
                <h1 class="fs-4 fw-bold">Lista de categorias</h1>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-categorias text-center" >
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($categorias as $categoria)
                                <tr>
                                    <td>{{ $categoria->nombre }}</td>
                                    <td>
                                        {{-- <a href="#" class="btn btn-outline-dark"><i class="fas fa-edit"></i> Editar</a> --}}
                                        <a href="#" class="btn btn-outline-danger"><i class="fas fa-trash-alt"></i> Eliminar</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Nombre</th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4 pb-3">
        <div class="card">
            <div class="card-header text-center bg-title">
                <h1 class="fs-4 fw-bold">Registrar Categoria</h1>
            </div>
            <form action="{{ route('categoria.store') }}" method="POST" class="form-group">
                @csrf
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Nombre</label>
                                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Ingresar Nombre">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-end">
                    <button type="submit" class="btn btn-primary"><i class="far fa-save"></i> Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
@push('scripts')
   <script src="{{ asset('js/datatables.min.js') }}"></script>
   <script>
       $(document).ready(function(){
        $('.dataTables-categorias').DataTable();
    });
   </script>
@endpush
@endsection